### ISSUE TITLE
HTTP 403 errors for ffightae_cps2.zip

### ISSUE THREAD

**Issue by prenetic** [zakk4223/ArcadeROMsDB_MiSTer#2]
Myself and others have noticed consistent failures for `ffightae_cps2.zip` lately.

```json
    "|games/mame/ffightae_cps2.zip": {
      "hash": "beb36389fa0db31e35fd6b27354a85f4",
      "size": 3893838,
      "tags": [0, 2, 3, 7],
      "url": "https://archive.org/download/arcade_offset/ffightae_cps2.zip"
    },
```

From `downloader.log`:
```
games/mame/ffightae_cps2.zip
Bad http status! games/mame/ffightae_cps2.zip: 403
```

Seems the item was pulled:
![image](https://github.com/zakk4223/ArcadeROMsDB_MiSTer/assets/11982895/b295578f-f316-416c-9484-1cf297aa41a9)

**Comment by prenetic** [comment]
From the MiSTer FPGA forums:
https://misterfpga.org/viewtopic.php?t=7982

**Comment by Toryalai1** [comment]
This should be solved now

**Comment by prenetic** [comment]
Thanks, confirming it works on my end.
```
/root# ls -l /media/fat/games/mame/ffightae_cps2.zip
-rwxr-xr-x 1 root root 3893838 Sep  3 07:51 /media/fat/games/mame/ffightae_cps2.zip
```

**Comment by hotelvictorcharlie** [comment]
Did this break the majority of the other downloads? Only 201 of the MAME games will download for me.
```
Errors:
1943kai.zip, alexkidd.zip, aso.zip, 1943mii.zip, avsp.zip, berabohm.zip, 1944.zip, bioatack.zip, blasto.zip, blktiger.zip, 1941.zip, blueshrk.zip, bodyslam.zip, bouldash.zip, 1942.zip, 1943.zip, 19xx.zip, boxyboy.zip, bublbobl.zip, 280zzzap.zip, 3wonders.zip, airduel.zip, captcomm.zip, carnival.zip, aliensyn.zip + other files.
```

The log shows a ton of these 403 (forbidden) errors. I guess the archive.org links are broken:
```
Bad http status! games/mame/1943kai.zip: 403
```

There was a similar issue in the past: https://github.com/theypsilon/Update_All_MiSTer/issues/119

**Comment by Toryalai1** [comment]
No.
The reason why you get that is because those links now requires login to access the files.

**Comment by hotelvictorcharlie** [comment]
> No. The reason why you get that is because those links now requires login to access the files.

Right, I'm suggesting that [today's change](https://github.com/zakk4223/ArcadeROMsDB_MiSTer/commit/ec3c0eff7260d33ad6db625cbc939639da4f545f) (which "fixed" this issue) updated the URL to the files from one where they are unlocked to one where they are locked (requiring login).

**Comment by zakk4223** [comment]
No, the original archive went login-required. The change you linked was reverted: that archive uses 7z files for a bunch of roms which the mister cannot handle.

A solution is being worked on
